# Plugin developed by Niketion, License: MIT
# Github: github.com/Niketion/ControlHacker
permission-denied: "&cYou don't have permission."
usage-controlhacker:
 - '&5/ch reload &7- Reload config'
 - '&5/ch setzone (cheater/checker/end) &7- Set various location'
 - '&5/ch stats <checker> &7- Check stats of a checker'
 - '&5/ch reset <checker> &7- Reset stats'
 - '&5/ch top &7- See top of checker'
zone-set: "&aZone %value% successfully set."
usage-control: "&aUsage: /control <player>"
usage-finish: "&aUsage: /finish <player>"
player-not-found: "&c%player% not found..."
stats-not-found: "&cStats of %player% not found..."
is-not-in-check: "&c%player% isn't in a check"
is-already-in-check: "&c%player% is already in check!"
cheater-is-quit: "&4&l[!!!] &c%player% quit during a control."
check-yourself:
 enabled: false
 message: "&cYou can't check yourself."
title:
  title-message: "&cCONTROL"
  subtitle-message: "&7by %player%"
checker-start-message: "&a%player% was teleported to zone of control, waiting for for his action..."
cheater-message:
 - "&4&lATTENTION!"
 - ""
 - "&7Give id skype/teamviewer/anydesk"
 - "&7to checker (%player%)"
 - "&cDON'T DISCONNECT or you'll be banned!"

old-finish: false # I would recommend using the new version
finish-cheater-message: "&aThanks for the pacience, control finished."
finish-checker-message: "&a%player% was teleport to end control."

cheater-control-gui:
  title: "&3&lControl"
  # multiple of 9 
  size: 27
  # You can add as many items as you want
  items:
    1:
      clayColor: 14
      slot: 11
      display-name: "&4&lAdmit Cheat"
      lore:
      - ""
      - "&c&lNOTICE:"
      - "&cIf you click this item"
      - "&cyou'll be instantly banned!"
      
      # END -> End the control (use it if you ban/kick the player)
      # CONTROL -> The control will proceed regularly
      action: END
      commands:
        # CONSOLE -> The commands will be executed by the console
        # CHECKER -> The commands will be executed by the "CHECKER"
        executor: CHECKER
        list:
        - "tempban 5d %cheater% Hack Admission"
    2:
      clayColor: 4
      slot: 15
      display-name: "&6&lProceed control"
      lore:
      - ""
      - "&7By clicking this item you"
      - "&7will be subject to a regular"
      - "&7control."
      action: CONTROL
      commands:
        executor: CONSOLE
        list:
        - "tell %checker% %cheater% accepted control!"
finish-gui-title: "&c&lFinish Control"
finish-first-option:
  display-name: "&e&lREFUSAL CONTROL/ADMISSION"
  lore:
  - ""
  - "&7The player will be banned"
  - "&7for 7 days"
  cmdsExecutor: CHECKER
  # Placeholders:
  # %checker% - %cheater%
  commands:
  - "tempban 5day %cheater% Refusal/admission control (Controlled by %checker%)"
finish-second-option:
  display-name: "&c&lHACK"
  lore:
  - ""
  - "&7The player will be banned"
  - "&7for 10 days"
  cmdsExecutor: CHECKER
  commands:
  - "tempban 10day %cheater% Hack (Controlled by %checker%)"
finish-third-option:
  display-name: "&a&lCLEAN"
  lore:
  - ""
  - "&7The console will broadcast"
  - "&7that the player isn't cheating"
  cmdsExecutor: CONSOLE
  commands:
  - "broadcast %cheater% doesn't have any hacks"

stats-deleted: "&aStats of %player% deleted."
stats-message:
  - "&aStats of %player%:"
  - "&aAll controls:&7 %value-1%"
  - "&aClean:&7 %value-2%"
  - "&aHack:&7 %value-3%"
  - "&aAdmission/Refusal:&7 %value-4%"

top-number: 10
top-null: "&cHistory not found..."
top-message:
  head: "&aTop checker &7(%date%)&a:"
  default: "#%number% &7%player% - %value%"

command-quit-from-control:
  enabled: true
  commands:
   - "tempban 5d %player% Quit during a control"
format-chat:
 format: "&c[%time%]&f %player%: %message%"
event:
  stop-command: true
  command-whitelisted:
   - "/f"
  stop-move: false
  stop-drop: true
  stop-break: true
  stop-place: true
  stop-damage: true