name: ControlHacker
version: 5.1.5
author: Niketion
main: niketion.github.controlhacker.bukkit.Main
commands:
  controlhacker:
    description: ControlHacker main command
    aliases: ch
  control:
    description: Control a cheater
  finish:
    description: Finish a control