#
# Niketion (InventionTeam) - ControlHacker
# OpenSource: github.com/Niketion/ControlHacker
#

version-config: 0.2a # Don't touch

#
#
#

prefix:
  prefix-normal: '&6&l> &e'
  prefix-error: '&4&l> &c'
permissions:
  denied: '&cPermission denied. &7(inv.nik.controlhacker.*)'
commands:
  args:
    not-found: |-
      &cArgs not found...
      &7> /ch reload - Reload Config.yml.
      &7> /ch setlocation (hacker/staffer/endcontrol) - Set location of control.
      &7> /control <player> - Control a player.
  player:
    not-found: '&ePlayer not found...'
    not-controlled: '&ePlayer isn''t in a control.'
    staffer-equals-hacker: '&cYou can''t control yourself.'
    hacker-is-staffer: '&cYou can''t control other staffer.'
    no-console: '&cThis command is executable by player.'
    already-control: '&cPlayer is already in a control.'
    start-control:
      staffer: '&eThe control started: %player%!'
      hacker:
        title: ''
        subtitle: '&cControl &lHACK&7 by %staffer%!'
        fade-in: 10
        fade-out: 10
    finish-control:
      staffer: '&eThe control finished: %player%!'
      teleport-hacker: '&eControl ended. You''re teleport to spawn by %staffer%'
    sound:
      finish-control:
        hacker: LEVEL_UP
      start-control:
        hacker: NOTE_BASS
        staffer: NOTE_PLING
control:
  command-deny: '&cThe commands aren''t allowed in a control.'
  quit-control: '&c%player% quit in a control!'
  format-chat: '&c&lCONTROL &7%player%: &f%message%'
  command-in-control: false
  block-break-in-control: false
  block-place-in-control: false
  entity-damage-in-control: false
  teleport-in-control: false
  drop-item-in-control: false
