#
# Niketion - ControlHacker
# OpenSource: github.com/Niketion/ControlHacker
#

Version-Config: 4.1 # Don't touch

Chat:
  Prefix: '&9ControlHacker>'
  Permission-Denied: '&7You don''t have permission.'
  Player-Not-Found: '&6%player%&7 not found...'
  Usage-Control: '&7Usage: /<command> <player>'
  Control-Yourself: '&7You can''t control yourself...'
  Already-Control: '&7Player is already in a control.'
  Start-Control:
    Staffer: '&7Ok, start the control to %player%'
    Hacker: |-
      &4&lALERT! &7The control is started by &d%player%!
      &7Give contact and don't quit the game!
  End-Control:
    Staffer: '&d%player%&7 is teleported to zone of endcontrol.'
    Hacker: '&7Thanks for the patience, control completed. You''re teleported at the spawn by &b%player%&7.'
  Quit: '&c%player%&7 is quit by a control.'
  Player-Not-Controlled: '&e%player%&7 isn''t in a control!'

Event:
  Format-Control: '&4&lCONTROL &7%player%: %message%'
  Command-Blocked: '&7All commands are disabled in the control.'
  Block-Break: false
  Block-Place: false
  Teleport: false
  Drop-Item: false
  Bow: false
  God: true

Report:
  Cooldown: 30 # seconds
  Cooldown-Message: '&7Wait &d%number% &7seconds...'
  Prefix: '&9Report>'
  Report-Message: |-
    &2&l&m=============================================
    &9Report> &7New report:
     &d%reported% &7is reported by &b%player%&7.
     &7Reason: &c%reason%
    &2&l&m=============================================
  Report-Usage: '&7Usage: /report <player> <text>'
  Report-Yourself: '&7You can''t report yourself...'
  Thanks-For-Report: '&7Thanks for reporting &d%player%&7.'
  Report-List-Format: '&9#%id% &c%reported% &7is reported by &b%reporter% &7for &6%reason%'
  No-Reports: '&eThere isn''t reports.'
  Reports-List: '&7List reports:'
  Usage-Args-List: '&7Usage: /lr closeall'
  All-Report-Closed: '&7All reports are closed.'

#
# Sound list:
#   1.8: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
#   1.9+: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
#

Sound:
  Start-Control: note-pling
  End-Control: note-bass

Title:
  Start-Control:
    Title: '&4&lCONTROL!'
    SubTitle: '&7by &c%player%'


