name: ControlHacker
version: 5.0.0
author: Niketion
main: niketion.github.controlhacker.Main
commands:
  controlhacker:
    description: ControlHacker main command
    aliases: ch
  control:
    description: Control a cheater
  finish:
    description: Finish a control