author: Niketion
version: 4.1
main: it.nik.controlhacker.Main
name: ControlHacker
softdepend: [TitleManager]
commands:
  controlhacker:
    description: A command of ControlHacker.
    usage: /<command> <arg> <arg>
    aliases: ch
  control:
    description: A command of ControlHacker.
    usage: /<command> <arg>
    aliases: controllo
  finish:
    description: A command of ControlHacker.
    usage: /<command> <arg>
    aliases: termina
  report:
    description: A command of ControlHacker.
    usage: /<command> <arg> <arg>
    aliases: segnala
  listreports:
     description: A command of ControlHacker.
     usage: /<command>
     aliases: lr
permissions:
  controlhacker.admin:
    children:
      controlhacker.mod: true
    default: op
  controlhacker.mod:
    default: op