name: ControlHacker
author: Niketion
version: 0.3b
main: it.niketion.controlhacker.Main
softdepends: [TitleManager]
commands:
  controlhacker:
    aliases: ch
    description: A command of ControlHacker.
    usage: /<command> <arg> <arg>
  control:
    description: A command of ControlHacker.
    usage: /<command> <player>
  finish:
    description: A command of ControlHacker.
    usage: /<command> <player>
permissions:
  inv.nik.controlhacker.*:
    children:
      inv.nik.controlhacker.operator: true
      inv.nik.controlhacker.mod: true
  inv.nik.controlhacker.operator:
    default: op
  inv.nik.controlhacker.mod:
    default: op
